# Generated by Django 4.2.16 on 2024-09-26 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('key', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('bool', 'Booléen'), ('int', 'Entier'), ('float', 'Flottant'), ('string', 'Chaine')], default='string', max_length=10)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('rencontre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rencontre')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Juge',
            fields=[
                ('profil_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pyInterClubs_admin.profil')),
                ('voies', models.ManyToManyField(related_name='juges', through='core.RencontreVoie', to='core.voie')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('pyInterClubs_admin.profil',),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('profil_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pyInterClubs_admin.profil')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.club')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('pyInterClubs_admin.profil',),
        ),
    ]
