# Generated by Django 4.1.5 on 2023-03-18 18:07

from django.db import migrations, models


def set_types(apps, schema_editor):
    model = apps.get_model('pyInterClubs_admin', 'Config')
    for c in model.objects.all():
        c.type = 'int'
        c.save(update_fields=['type'])


class Migration(migrations.Migration):

    dependencies = [
        ('pyInterClubs_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='type',
            field=models.CharField(choices=[('bool', 'Booléen'), ('int', 'Entier'), ('float', 'Flottant'), ('string', 'Chaine')], default='string', max_length=10),
        ),
        migrations.RunPython(set_types),
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
