# Generated by Django 4.2.16 on 2024-09-26 00:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'ordering': ['club_id', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Grimpeur',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('anneeNaissance', models.IntegerField()),
                ('sexe', models.IntegerField(choices=[(None, 'Sélectionnez le genre'), (1, 'Fille'), (2, 'Garçon'), (3, 'Mixte')])),
                ('licence', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('temps', models.DurationField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('etat', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rencontre',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('saison', models.IntegerField()),
                ('date', models.DateField()),
                ('categorie', models.IntegerField(choices=[(None, 'Sélectionnez la catégorie'), (1, 'Enfants'), (2, 'Adolescents')])),
                ('nbBloc', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('nbDiff', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('nbVitesse', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('voiesReutilisables', models.BooleanField(default=False)),
                ('voiesGroupees', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RencontreVoie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'rencontre-voie',
                'verbose_name_plural': 'rencontres-voies',
            },
        ),
        migrations.CreateModel(
            name='Voie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=15)),
                ('niveau', models.CharField(max_length=5)),
                ('categorie', models.IntegerField(choices=[(None, 'Sélectionnez la catégorie'), (1, 'Enfants'), (2, 'Adolescents')])),
                ('type', models.IntegerField(choices=[(None, 'Sélectionnez le type'), (1, 'Bloc'), (2, 'Difficulté'), (3, 'Vitesse')])),
                ('zones', models.JSONField()),
                ('actif', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['type'], name='core_voie_type_1788b7_idx'), models.Index(fields=['actif'], name='core_voie_actif_5b08e8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordre', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)])),
                ('clubPreteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.club')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membres', to='core.equipe')),
                ('grimpeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='core.grimpeur')),
            ],
            options={
                'ordering': ['equipe_id', 'ordre'],
            },
        ),
    ]
