# Generated by Django 4.2.10 on 2024-03-04 22:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('ville', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipes', to='core.club')),
            ],
        ),
        migrations.CreateModel(
            name='Grimpeur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('anneeNaissance', models.IntegerField()),
                ('sexe', models.IntegerField(choices=[(None, 'Sélectionnez le genre'), (1, 'Fille'), (2, 'Garçon'), (3, 'Mixte')])),
                ('licence', models.BigIntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Grimpeurs', to='core.club')),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=10)),
                ('niveau', models.CharField(max_length=5)),
                ('type', models.IntegerField(choices=[(None, 'Sélectionnez le type'), (1, 'Bloc'), (2, 'Difficulté'), (3, 'Vitesse')])),
                ('zones', models.JSONField()),
                ('actif', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('annee', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.IntegerField(default=0)),
                ('ordre', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)])),
                ('clubPreteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.club')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='core.equipe')),
                ('grimpeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='core.grimpeur')),
            ],
        ),
        migrations.CreateModel(
            name='Rencontre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('categorie', models.IntegerField(choices=[(None, 'Sélectionnez la catégorie'), (1, 'Enfants'), (2, 'Adolescents')])),
                ('nbBloc', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('nbDiff', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)])),
                ('nbVitesse', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('voieReutilisable', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rencontres', to='core.club')),
                ('saison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rencontres', to='core.saison')),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temps', models.DurationField(null=True)),
                ('points', models.IntegerField(default=0, null=True)),
                ('etat', models.IntegerField()),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.niveau')),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.score')),
            ],
        ),
        migrations.CreateModel(
            name='Juge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.niveau')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='rencontre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipes', to='core.rencontre'),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.club')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
