# Generated by Django 4.2.16 on 2024-09-26 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pyInterClubs_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rencontrevoie',
            name='juge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pyInterClubs_admin.juge'),
        ),
        migrations.AddField(
            model_name='rencontrevoie',
            name='rencontre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rencontre'),
        ),
        migrations.AddField(
            model_name='rencontrevoie',
            name='voie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.voie'),
        ),
        migrations.AddField(
            model_name='rencontre',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rencontres', to='core.club'),
        ),
        migrations.AddField(
            model_name='rencontre',
            name='voies',
            field=models.ManyToManyField(through='core.RencontreVoie', to='core.voie'),
        ),
        migrations.AddField(
            model_name='performance',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='core.score'),
        ),
        migrations.AddField(
            model_name='performance',
            name='voie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.voie'),
        ),
        migrations.AddField(
            model_name='grimpeur',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grimpeurs', to='core.club'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipes', to='core.club'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='rencontre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipes', to='core.rencontre'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['equipe'], name='core_score_equipe__4a0a57_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['grimpeur'], name='core_score_grimpeu_1e9d3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='rencontrevoie',
            constraint=models.UniqueConstraint(fields=('rencontre', 'voie'), name='unique_rencontre_voie'),
        ),
        migrations.AddIndex(
            model_name='rencontre',
            index=models.Index(fields=['categorie'], name='core_rencon_categor_f919f4_idx'),
        ),
        migrations.AddIndex(
            model_name='rencontre',
            index=models.Index(fields=['date'], name='core_rencon_date_07a6c9_idx'),
        ),
        migrations.AddIndex(
            model_name='rencontre',
            index=models.Index(fields=['saison'], name='core_rencon_saison_48c426_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['voie_id'], name='core_perfor_voie_id_4e29fe_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['score_id'], name='core_perfor_score_i_db0a33_idx'),
        ),
        migrations.AddIndex(
            model_name='performance',
            index=models.Index(fields=['temps'], name='core_perfor_temps_495518_idx'),
        ),
        migrations.AddIndex(
            model_name='grimpeur',
            index=models.Index(fields=['anneeNaissance'], name='core_grimpe_anneeNa_0f51bc_idx'),
        ),
        migrations.AddIndex(
            model_name='grimpeur',
            index=models.Index(fields=['sexe'], name='core_grimpe_sexe_3ccca0_idx'),
        ),
        migrations.AddIndex(
            model_name='equipe',
            index=models.Index(fields=['club'], name='core_equipe_club_id_109520_idx'),
        ),
        migrations.AddIndex(
            model_name='equipe',
            index=models.Index(fields=['rencontre'], name='core_equipe_rencont_954a59_idx'),
        ),
    ]
