# Generated by Django 4.1.3 on 2022-11-27 19:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='Localisation',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='club',
            name='Nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='Categorie',
            field=models.IntegerField(choices=[(None, 'Sélectionnez la catégorie'), (1, 'Enfants'), (2, 'Adolescents')]),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='Club',
            field=models.ForeignKey(db_column='IDClub', on_delete=django.db.models.deletion.PROTECT, related_name='Equipes', to='core.club'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='Numero',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='Rencontre',
            field=models.ForeignKey(db_column='IDRencontre', on_delete=django.db.models.deletion.PROTECT, related_name='Equipes', to='core.rencontre'),
        ),
        migrations.AlterField(
            model_name='grimpeur',
            name='AnneeNaissance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='grimpeur',
            name='Club',
            field=models.ForeignKey(db_column='IDClub', on_delete=django.db.models.deletion.PROTECT, related_name='Grimpeurs', to='core.club'),
        ),
        migrations.AlterField(
            model_name='grimpeur',
            name='Licence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='grimpeur',
            name='Nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='grimpeur',
            name='Prenom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='grimpeur',
            name='Sexe',
            field=models.IntegerField(choices=[(None, 'Sélectionnez le genre'), (1, 'Fille'), (2, 'Garçon'), (3, 'Mixte')]),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='Actif',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='Categorie',
            field=models.IntegerField(choices=[(None, 'Sélectionnez la catégorie'), (1, 'Enfants'), (2, 'Adolescents')]),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='NiveauVoie',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='NomVoie',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='PtsValorises',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='PtsVoieComplete',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rencontre',
            name='Club',
            field=models.ForeignKey(db_column='IDClub', on_delete=django.db.models.deletion.PROTECT, related_name='Rencontres', to='core.club'),
        ),
        migrations.AlterField(
            model_name='rencontre',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rencontre',
            name='Saison',
            field=models.ForeignKey(db_column='IDSaison', on_delete=django.db.models.deletion.PROTECT, related_name='Rencontres', to='core.saison'),
        ),
        migrations.AlterField(
            model_name='saison',
            name='Annee',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='Equipe',
            field=models.ForeignKey(db_column='IDEquipe', on_delete=django.db.models.deletion.PROTECT, related_name='Scores', to='core.equipe'),
        ),
        migrations.AlterField(
            model_name='score',
            name='Grimpeur',
            field=models.ForeignKey(db_column='IDGrimpeur', on_delete=django.db.models.deletion.PROTECT, related_name='Scores', to='core.grimpeur'),
        ),
        migrations.AlterField(
            model_name='score',
            name='Ordre',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='score',
            name='Points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='PtsVitesse',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='Vitesse',
            field=models.BigIntegerField(default=0),
        ),
    ]
