# Generated by Django 4.2.11 on 2024-07-16 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('pyInterClubs_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rencontrevoie',
            name='juge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pyInterClubs_admin.juge'),
        ),
        migrations.AddField(
            model_name='rencontrevoie',
            name='rencontre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rencontre'),
        ),
        migrations.AddField(
            model_name='rencontrevoie',
            name='voie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.voie'),
        ),
        migrations.AddField(
            model_name='rencontre',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rencontres', to='core.club'),
        ),
        migrations.AddField(
            model_name='rencontre',
            name='voies',
            field=models.ManyToManyField(through='core.RencontreVoie', to='core.voie'),
        ),
        migrations.AddField(
            model_name='performance',
            name='score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='core.score'),
        ),
        migrations.AddField(
            model_name='performance',
            name='voie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.voie'),
        ),
        migrations.AddField(
            model_name='grimpeur',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grimpeurs', to='core.club'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipes', to='core.club'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='rencontre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipes', to='core.rencontre'),
        ),
        migrations.AddConstraint(
            model_name='rencontrevoie',
            constraint=models.UniqueConstraint(fields=('rencontre', 'voie'), name='unique_rencontre_voie'),
        ),
        migrations.AddIndex(
            model_name='rencontre',
            index=models.Index(fields=['categorie'], name='core_rencon_categor_f919f4_idx'),
        ),
        migrations.AddIndex(
            model_name='rencontre',
            index=models.Index(fields=['date'], name='core_rencon_date_07a6c9_idx'),
        ),
        migrations.AddIndex(
            model_name='grimpeur',
            index=models.Index(fields=['anneeNaissance'], name='core_grimpe_anneeNa_0f51bc_idx'),
        ),
        migrations.AddIndex(
            model_name='grimpeur',
            index=models.Index(fields=['sexe'], name='core_grimpe_sexe_3ccca0_idx'),
        ),
    ]
