# Generated by Django 4.1.5 on 2023-03-25 01:24

from django.db import migrations, models


def alter_vitesses(apps, schema_editor):
    Score = apps.get_model('core', 'Score')
    for s in Score.objects.all():
        v = s.Vitesse
        if v > 0: v = int(v / 10)
        if v ==  -600000000: v = -1 # Chute
        if v == -1200000000: v = -2 # Abandon
        s.Vitesse = v
        s.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_nullables'),
    ]

    operations = [
        migrations.RunPython(alter_vitesses),
        migrations.AlterField(
            model_name='score',
            name='Vitesse',
            field=models.DurationField(default=0),
        ),
    ]
