# Generated by Django 4.1.7 on 2023-04-02 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_score_vitesse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='Numero',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
